name: instagramz_clone
description: A new Flutter project.

publish_to: 'none'

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^4.8.4
  cupertino_icons: ^1.0.2
  uuid: ^3.0.7
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  firebase_storage: ^11.2.5
  hooks_riverpod: ^2.2.0
  flutter_hooks: ^0.20.0
  font_awesome_flutter: ^10.5.0
  flutter_facebook_auth: ^6.0.1
  image: ^4.0.17
  image_picker: ^1.0.2
  collection: ^1.17.1
  video_thumbnail: ^0.5.3
  video_player: ^2.7.0
  lottie: ^2.5.0
  share_plus: ^7.1.0
  url_launcher: ^6.1.12
  riverpod_annotation: ^2.1.1
  intl: ^0.18.1
  google_sign_in: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  riverpod_generator: ^2.2.5
  
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/animations/empty.json
    - assets/animations/loading.json
    - assets/animations/data_not_found.json
    - assets/animations/error.json
    - assets/animations/small_error.json

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
